### ISSUE TITLE
Use smaller assets for poster image preview

### ISSUE THREAD

**Issue by gidsg** [guardian/media-atom-maker#175]
# Steps to reproduce

Go to: `/video/videos`

# Actual Results
Poster images use largest asset which is scaled down in the browser:

![screen shot 2017-01-09 at 10 30 43](https://cloud.githubusercontent.com/assets/1764158/21763656/db009c22-d656-11e6-8f28-5abeb602e461.png)

# Expected Results
Use closest available image asset to the desired display resolution

**Comment by ShaunYearStrong** [comment]
👍 for this. One of the microservices in the grid handles creating the correct images for thumbs and full previews. We could look at adding something similar here.

**Comment by paperboyo** [comment]
😆 On the next page the thumbnail is used again, but this time it uses a standard 500px Grid crop. It is slightly bigger than displayed at 100% zoom, but will provide a nicer rendering on HiDPI displays because of that. Every Grid image should have a 500px crop *unless* the original crop is less than 500px (unlikely, but would be nice to have a fallback).

![picture 88](https://cloud.githubusercontent.com/assets/6032869/22314966/f523bda2-e35b-11e6-9a19-eec9bef21d18.png)
